In [2]:
import torch

In [38]:
model = torch.load(f'result/2024/model_0.pth', weights_only=False)
model0 = torch.load(f'result/2024/model_0.pth', weights_only=False)
model1 = torch.load(f'result/2024/model_1.pth', weights_only=False)
model2 = torch.load(f'result/2024/model_2.pth', weights_only=False)
model3 = torch.load(f'result/2024/model_3.pth', weights_only=False)

In [39]:
state_dict = model.state_dict()
state_dict0 = model0.state_dict()
state_dict1 = model1.state_dict()
state_dict2 = model2.state_dict()
state_dict3 = model3.state_dict()

In [73]:
for k in state_dict:
    state_dict[k] = torch.stack([
        state_dict0[k],
        state_dict1[k],
        state_dict2[k],
        state_dict3[k],
    ]).mean(dim=0)

In [74]:
state_dict['cls_token'].shape

torch.Size([1, 1, 2048])

In [61]:
state_dict1['cls_token'].shape

torch.Size([1, 1, 2048])

In [62]:
state_dict['cls_token']

tensor([[ 0.0062, -0.0011, -0.0236,  ...,  0.0220, -0.0128,  0.0051]],
       device='cuda:0')

In [63]:
state_dict0['cls_token']

tensor([[[ 0.0055, -0.0017, -0.0240,  ...,  0.0210, -0.0109,  0.0043]]],
       device='cuda:0')

In [64]:
state_dict1['cls_token']

tensor([[[ 0.0051, -0.0019, -0.0227,  ...,  0.0206, -0.0137,  0.0044]]],
       device='cuda:0')

In [65]:
state_dict2['cls_token']

tensor([[[ 0.0071, -0.0001, -0.0233,  ...,  0.0242, -0.0140,  0.0045]]],
       device='cuda:0')

In [66]:
state_dict3['cls_token']

tensor([[[ 0.0072, -0.0007, -0.0245,  ...,  0.0220, -0.0129,  0.0073]]],
       device='cuda:0')

In [68]:
(55+51+71+72)/4

62.25

In [54]:
[state_dict0['cls_token'].detach()]

[tensor([[[ 0.0055, -0.0017, -0.0240,  ...,  0.0210, -0.0109,  0.0043]]],
        device='cuda:0')]

In [72]:
torch.stack([
        state_dict0['cls_token'],
        state_dict1['cls_token'],
        state_dict2['cls_token'],
        state_dict3['cls_token'],
    ]).mean(dim=0)

tensor([[[ 0.0062, -0.0011, -0.0236,  ...,  0.0220, -0.0128,  0.0051]]],
       device='cuda:0')

In [14]:
len(state_dict)

27

In [17]:
for k in state_dict:
    print(k)

cls_token
blocks.0.norm1.weight
blocks.0.norm1.bias
blocks.0.attn.qkv.weight
blocks.0.attn.proj.weight
blocks.0.attn.proj.bias
blocks.0.norm2.weight
blocks.0.norm2.bias
blocks.0.mlp.fc1.weight
blocks.0.mlp.fc1.bias
blocks.0.mlp.fc2.weight
blocks.0.mlp.fc2.bias
blocks.1.norm1.weight
blocks.1.norm1.bias
blocks.1.attn.qkv.weight
blocks.1.attn.proj.weight
blocks.1.attn.proj.bias
blocks.1.norm2.weight
blocks.1.norm2.bias
blocks.1.mlp.fc1.weight
blocks.1.mlp.fc1.bias
blocks.1.mlp.fc2.weight
blocks.1.mlp.fc2.bias
norm.weight
norm.bias
slide_head.weight
slide_head.bias


In [21]:
state_dict['cls_token'].shape

torch.Size([1, 1, 2048])

In [22]:
type(state_dict)

collections.OrderedDict

In [30]:
state_dict['cls_token'] = 1

In [31]:
state_dict['cls_token']

1

In [32]:
state_dict

OrderedDict([('cls_token', 1),
             ('blocks.0.norm1.weight',
              tensor([1.0000, 0.9987, 1.0008,  ..., 0.9994, 1.0032, 0.9999], device='cuda:0')),
             ('blocks.0.norm1.bias',
              tensor([ 6.2910e-04,  5.4355e-04, -1.7773e-05,  ..., -3.2562e-04,
                      -2.0259e-04,  6.1433e-06], device='cuda:0')),
             ('blocks.0.attn.qkv.weight',
              tensor([[ 4.1729e-03,  4.2027e-05,  1.3835e-02,  ..., -1.9528e-03,
                        4.0002e-02, -2.7748e-02],
                      [-2.5255e-03,  1.2616e-02,  1.4667e-02,  ...,  1.7314e-02,
                       -1.1231e-02,  4.6742e-03],
                      [-1.2294e-02, -2.7782e-02,  6.5948e-04,  ...,  2.1454e-02,
                        1.4629e-02, -3.3933e-03],
                      ...,
                      [ 1.9883e-02, -4.0539e-03,  8.2097e-03,  ..., -3.1096e-03,
                        7.0767e-04,  7.4559e-03],
                      [ 1.0385e-02,  1.0185e-02,  2.6984